### ISSUE TITLE
File specified are missing or source is not available

### ISSUE THREAD

**Issue by dhayalanms** [geerlingguy/drupalci-sonar-jenkins#20]
The sonar no longer available on codehaus since codehaus was closed for good (http://www.javaworld.com/article/2892227/open-source-tools/codehaus-the-once-great-house-of-code-has-fallen.html)
The Sonnar installation xml and Sonar runner xml is not available under the jenkins
Unable to find these two files
/vagrant/config/jenkins/drupal-7-example/build.xml
/vagrant/config/jenkins/drupal-7-example/sonar-project.properties

The sonar jenkins plugin latest version doesnt have "Invoke Standalone Sonar Analysis"

**Comment by scottrigby** [comment]
The codehaus issue is fixed in #23.

This issue is different: there are unneeded commas in the YAML definition, which are read as part of the file name. See this message:

```shell
TASK [Copy Sonar Jenkins configuration to server.] *****************************
failed: [drupalci] (item={u'dest': u'/var/lib/jenkins/hudson.plugins.sonar.SonarPublisher.xml', u'src': u'jenkins/hudson.plugins.sonar.SonarPublisher.xml.j2,'}) => {"failed": true, "item": {"dest": "/var/lib/jenkins/hudson.plugins.sonar.SonarPublisher.xml", "src": "jenkins/hudson.plugins.sonar.SonarPublisher.xml.j2,"}, "msg": "Unable to find 'jenkins/hudson.plugins.sonar.SonarPublisher.xml.j2,' in expected paths."}
failed: [drupalci] (item={u'dest': u'/var/lib/jenkins/hudson.plugins.sonar.SonarRunnerInstallation.xml', u'src': u'jenkins/hudson.plugins.sonar.SonarRunnerInstallation.xml.j2,'}) => {"failed": true, "item": {"dest": "/var/lib/jenkins/hudson.plugins.sonar.SonarRunnerInstallation.xml", "src": "jenkins/hudson.plugins.sonar.SonarRunnerInstallation.xml.j2,"}, "msg": "Unable to find 'jenkins/hudson.plugins.sonar.SonarRunnerInstallation.xml.j2,' in expected paths."}
```

Specifically:
`jenkins/hudson.plugins.sonar.SonarPublisher.xml.j2,` and `jenkins/hudson.plugins.sonar.SonarRunnerInstallation.xml.j2,` have a comma at the end, so the files (which do exist [here](https://github.com/geerlingguy/drupalci-sonar-jenkins/blob/master/provisioning/templates/jenkins/hudson.plugins.sonar.SonarPublisher.xml.j2) and [here](https://github.com/geerlingguy/drupalci-sonar-jenkins/blob/master/provisioning/templates/jenkins/hudson.plugins.sonar.SonarRunnerInstallation.xml.j2)) can not be found by Ansible.
